# Hourly scraping
name: R tweets

# Controls when the action will run.
on:
  schedule:
  - cron: '10 8 * * *'

jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
    
    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("rtweet", dependencies=TRUE)'
        R -e 'install.packages("tidyverse", dependencies=TRUE)'
        R -e 'install.packages("visNetwork", dependencies=TRUE)'
        R -e 'install.packages("tm", dependencies=TRUE)'
        R -e 'install.packages("RJSONIO", dependencies=TRUE)'
        R -e 'install.packages("RCurl", dependencies=TRUE)'
        R -e 'install.packages("syuzhet", dependencies=TRUE)'
        R -e 'install.packages("lubridate", dependencies=TRUE)'
        R -e 'install.packages("xts", dependencies=TRUE)'
        R -e 'install.packages("visNetwork", dependencies=TRUE)'
    
    # Run R script
    - name: Scrape
      run: Rscript tw_tweets.R
      
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data_output
        git commit -m "GH ACTION Headlines $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
